clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  ssh:
    image: appleboy/drone-ssh
    pull: true
    host: 192.168.25.202
    username: edison
    secrets:
      - source: edison
        target: ssh_password
    port: 22
    script:
      - echo hello
      - echo world

  scp:
    image: appleboy/drone-scp
    host: 192.168.25.202
    username: edison
    secrets:
      - source: edison
        target: ssh_password
    port: 22
    target: /home/drone/ichiro
    source: /root/drone-line
    when:
      status:  [ success ]

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0

  redis:
    image: redis:latest

  postgres:
    image: postgres:9.5.5
    environment:
      - POSTGRES_DB=homestead
      - POSTGRES_USER=homestead
      - POSTGRES_PASSWORD=secret
