clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  scp:
    image: appleboy/drone-scp
    host: 139.59.123.108
    username: drone
    password: 1234567890
    port: 22
    target: /home/drone/ichiro
    source: /root/drone-line/


services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0

  redis:
    image: redis:latest

  postgres:
    image: postgres:9.5.5
    environment:
      - POSTGRES_DB=homestead
      - POSTGRES_USER=homestead
      - POSTGRES_PASSWORD=secret
