clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  ssh:
    image: appleboy/drone-ssh
    pull: true
    host: 192.168.25.202
    username: edison
    secrets:
      - source: edison
        target: ssh_password
    port: 22
    script:
      - echo hello
      - echo world
  line:
    image: appleboy/drone-line
    channel_secret: 6668659454ee84bdb5f3ea0932ab83cd
    channel_token: ILSeSl4fALYomdzwx33EapLrOA5O/lsQIZOVYAOM5EpKp+zG1LlpCSAyfQ9ogv82CO7fR6LEzS4YK0G+q/MvwuHCgTH4c1H3KSSXllStZusuDl6ce+rgSo8eMlQDye2v3rvcGFx7QTBDcshXmAVWxAdB04t89/1O/w1cDnyilFU=
    to: U664ba5a51f1e2d2a77306a18385dfc0b
    message: ichiro
    
  ssh:
    image: appleboy/drone-ssh
    pull: true
    host: 192.168.25.202
    username: edison
    secrets:
      - source: edison
        target: ssh_password
    port: 22
    script:
      - sudo docker ps
    when:
      status:  [ success ]

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0

  redis:
    image: redis:latest

  postgres:
    image: postgres:9.5.5
    environment:
      - POSTGRES_DB=homestead
      - POSTGRES_USER=homestead
      - POSTGRES_PASSWORD=secret
